<form name="form1" id="form1" action="/action_page.php">
    Weapons: <select name="weapon" id="weapon">
        <option value="long">Berthier Mle 1892</option>
        <option value="long">Berthier Mle 1893 Deadeye</option>
        <option value="long">Berthier Mle 1893 Riposte</option>
        <option value="special">Bomb Lance</option>
        <option value="compact pistol">Bornheim No. 3</option>
        <option value="compact pistol">Bornheim No. 3 Extended</option>
        <option value="compact">Bornheim No. 3 Match</option>
        <option value="compact pistol">Caldwell 92 New Army</option>
        <option value="compact pistol">Caldwell Conversion Chain Pistol</option>
        <option value="compact pistol">Caldwell Conversion Pistol</option>
        <option value="long pistol">	Caldwell Conversion Uppercut</option>
        <option value="medium pistol">Caldwell Pax</option>
        <option value="medium pistol">Caldwell Pax Claw</option>
        <option value="shotgun">Caldwell Rival 78</option>
        <option value="shotgun">Caldwell Rival 78 Handcannon</option>
        <option value="special">Calvary Saber</option>
        <option value="special">Combat Axe</option>
        <option value="special">Crossbow</option>
        <option value="shotgun">Crown &amp; King Auto-5</option>
        <option value="medium pistol">Dolch 96</option>
        <option value="medium pistol">Dolch 96 Precision</option>
        <option value="special">Hand Crossbow</option>
        <option value="special">Hunting Bow</option>
        <option value="long">Lebel 1886</option>
        <option value="long">Lebel 1886 Aperture</option>
        <option value="long">Lebel 1886 Marksman</option>
        <option value="long">Lebel 1886 Talon</option>
        <option value="compact pistol">Lemat Mark II</option>
        <option value="special">Machete</option>
        <option value="long">Martini-Henry IC1</option>
        <option value="long">Martini-Henry IC1 Deadeye</option>
        <option value="long">Martini-Henry IC1 Marksman</option>
        <option value="long">Martini-Henry IC1 Riposte</option>
        <option value="long">Mosin-Nagant M1891</option>
        <option value="long">Mosin-Nagant M1891 Avtomat</option>
        <option value="long">Mosin-Nagant M1891 Bayonet</option>
        <option value="long">Mosin-Nagant M1891 Obrez</option>
        <option value="long">Mosin-Nagant M1891 Obrez Drum</option>
        <option value="long">Mosin-Nagant M1891 Obrez Mace</option>
        <option value="long">Mosin-Nagant M1891 Sniper</option>
        <option value="compact pistol">Nagant M1895</option>
        <option value="compact pistol">Nagant M1895 Deadeye</option>
        <option value="compact pistol">Nagant M1895 Officer</option>
        <option value="compact pistol">Nagant M1895 Officer Brawler</option>
        <option value="compact pistol">Nagant M1895 Officer Carbine</option>
        <option value="compact pistol">Nagant M1895 Officer Carbine Deadeye</option>
        <option value="compact pistol">Nagant M1895 Precision</option>
        <option value="compact silenced pistol">Nagant M1895 Silencer</option>
        <option value="nitro">Nitro Express Rifle</option>
        <option value="shotgun">Romero 77</option>
        <option value="shotgun">Romero 77 Alamo</option>
        <option value="shotgun">Romero 77 Handcannon</option>
        <option value="shotgun">Romero 77 Hatchet</option>
        <option value="shotgun">Romero 77 Talon</option>
        <option value="medium pistol">Scottfield Model 03</option>
        <option value="medium pistol">Scottfield Model 03 Brawler</option>
        <option value="medium pistol">Scottfield Model 03 Precision</option>
        <option value="medium pistol">Scottfield Model 03 Spitfire</option>
        <option value="medium pistol">Scottfield Model 03 Swift</option>
        <option value="long">Sparks LRR</option>
        <option value="long silenced">Sparks LRR Silencer</option>
        <option value="long">Sparks LRR Sniper</option>
        <option value="long pistol">Sparks Pistol</option>
        <option value="shotgun">Specter 1882</option>
        <option value="shotgun">Specter 1882 Bayonet</option>
        <option value="shotgun">Specter 1882 Compact</option>
        <option value="medium">Springfield 1866</option>
        <option value="medium">Springfield 1866 Compact</option>
        <option value="medium">Springfield 1866 Compact Deadeye</option>
        <option value="medium">Springfield 1866 Compact Striker</option>
        <option value="medium">Springfield 1866 Marksman</option>
        <option value="medium">Vetterli 71 Karabiner</option>
        <option value="medium">Vetterli 71 Karabiner Bayonet</option>
        <option value="medium">Vetterli 71 Karabiner Deadeye</option>
        <option value="medium">Vetterli 71 Karabiner Marksman</option>
        <option value="medium silenced">Vetterli 71 Karabiner Silencer</option>
        <option value="shotgun">Winfield 1887 Terminus</option>
        <option value="shotgun">Winfield 1887 Terminus Handcannon</option>
        <option value="shotgun">Winfield 1893 Slate</option>
        <option value="compact">Winfield M1873 </option>
        <option value="compact">Winfield M1873 Aperture</option>
        <option value="compact">Winfield M1873 Musket Bayonet</option>
        <option value="compact">Winfield M1873 Swift</option>
        <option value="compact">Winfield M1873 Talon</option>
        <option value="compact">Winfield M1873C</option>
        <option value="compact">Winfield M1873C Marksman</option>
        <option value="compact silenced">Winfield M1873C Silencer</option>
        <option value="compact">Winfield M1873C Vandal</option>
        <option value="compact">Winfield M1873C Vandal Deadeye</option>
        <option value="compact">Winfield M1873C Vandal Striker</option>
        <option value="medium">Winfield M1876 Centennial</option>
        <option value="medium">Winfield M1876 Centennial Sniper</option>
    </select>	
    Custom Ammo: <select>
        <option value="basic">Basic</option>
        <option value="fmj">Full Metal Jacket</option>
        <option value="spitzer">Spitzer</option>
    </select>
</form>
